### ISSUE TITLE
Scene: A 'text' device_feature can't be controlled in the "Set device state" action

### ISSUE THREAD

**Issue by StephBob** [GladysAssistant/Gladys#2026] opened 2024-02-11 18:43 UTC
Related to the subject : [Un topic MQTT de type ‘texte’ n’est plus ‘contrôlable’ dans une scène](https://community.gladysassistant.com/t/un-topic-mqtt-de-type-texte-nest-plus-controlable-dans-une-scene/8719)

**Describe the bug**
When a MQTT topic is created in Gladys with the type 'text', this topic can not be modified from a scene with the action "Controler un appareil". There are two different bahaviour (and both are not the expected behaviour):

- if I try to define a 'simple' value, the scene can not be saved
- if I try define a 'calculated' value, the scene is correctly saved, but the topic is not modifier when the scene is executed

**Comment by Pierre-Gilles** [comment] 2024-03-08 08:46
Closing this as it's not a bug: 

https://community.gladysassistant.com/t/un-topic-mqtt-de-type-texte-nest-plus-controlable-dans-une-scene/8719/13?u=pierre-gilles

**Closed as completed by Pierre-Gilles** 2024-03-08 08:46 UTC
